Can now accept any combination of local and remote .zips.

diff --git a/validate b/validate
--- a/validate
+++ b/validate
@@ -2,21 +2,21 @@
 
 WORKING_DIR="./tmp-validator";
 WGET_LOG_PATH="$WORKING_DIR/wget.log";
-REMOTE_ZIP_PATH="$WORKING_DIR/remote.zip";
-REMOTE_INFLATED_PATH="$WORKING_DIR/remote-inflated";
-LOCAL_INFLATED_PATH="$WORKING_DIR/local-inflated";
-REMOTE_SERIALIZED_PATH="$WORKING_DIR/remote-serialized";
-LOCAL_SERIALIZED_PATH="$WORKING_DIR/local-serialized";
+RIGHT_ZIP_PATH="$WORKING_DIR/right.zip";
+RIGHT_INFLATED_PATH="$WORKING_DIR/right-inflated";
+LEFT_INFLATED_PATH="$WORKING_DIR/left-inflated";
+RIGHT_SERIALIZED_PATH="$WORKING_DIR/right-serialized";
+LEFT_SERIALIZED_PATH="$WORKING_DIR/left-serialized";
 
-LOCAL_ZIP=$1;
-REMOTE_ZIP_URL=$2;
+LEFT_ZIP=$1;
+RIGHT_ZIP=$2;
 
-if [ -z $LOCAL_ZIP ] || [ -z $REMOTE_ZIP_URL ]; then
-	echo "Two arguments are required: path to the local .zip file, and URL of the remote .zip file.";
+if [ -z $LEFT_ZIP ] || [ -z $RIGHT_ZIP ]; then
+	echo "Two arguments are required: a path or URL to two .zip files.";
 	exit -1;
 fi 
 
-echo "Validating equality between local .zip [$LOCAL_ZIP] and remote .zip [$REMOTE_ZIP_URL].";
+echo "Validating equality between left .zip [$LEFT_ZIP] and right .zip [$RIGHT_ZIP].";
 
 if [ -d $WORKING_DIR ]; then 
 	echo "Working directory [$WORKING_DIR] already exists, cleaning up.";
@@ -30,52 +30,70 @@ if [ $? -ne 0 ]; then
 	exit -1;
 fi
 
-echo "Downloading remote .zip [$REMOTE_ZIP_URL].";
-wget -o $WGET_LOG_PATH -O $REMOTE_ZIP_PATH -- $REMOTE_ZIP_URL;
-if [ $? -ne 0 ]; then 
-	echo "Failed to download remote .zip [$REMOTE_ZIP_URL]:";
-	cat $WGET_LOG_PATH;
-	exit -1;
+if [[ $LEFT_ZIP == http* ]]; then
+	echo "Left .zip is remote, downloading from [$LEFT_ZIP].";
+	wget -o $WGET_LOG_PATH -O $LEFT_ZIP_PATH -- $LEFT_ZIP;
+	if [ $? -ne 0 ]; then 
+		echo "Failed to download left .zip from [$LEFT_ZIP].";
+		cat $WGET_LOG_PATH;
+		exit -1;
+	fi
+
+	rm $WGET_LOG_PATH;
+else 
+	echo "Left .zip is local [$LEFT_ZIP].";
 fi
 
-echo "Inflating remote .zip.";
-unzip -q $REMOTE_ZIP_PATH -d $REMOTE_INFLATED_PATH;
+if [[ $RIGHT_ZIP == http* ]]; then 
+	echo "Right .zip is remote, downloading from [$RIGHT_ZIP].";
+	wget -o $WGET_LOG_PATH -O $RIGHT_ZIP_PATH -- $RIGHT_ZIP;
+	if [ $? -ne 0 ]; then 
+		echo "Failed to download right .zip from [$RIGHT_ZIP].";
+		cat $WGET_LOG_PATH;
+		exit -1;
+	fi
+else
+	echo "Right .zip is local [$RIGHT_ZIP].";
+fi
+
+echo "Inflating right .zip.";
+unzip -q $RIGHT_ZIP_PATH -d $RIGHT_INFLATED_PATH;
 if [ $? -ne 0 ]; then 
-	echo "Failed to inflate remote .zip.";
+	echo "Failed to inflate right .zip.";
 	exit -1;
 fi 
 
-echo "Inflating local .zip [$LOCAL_ZIP].";
-unzip -q $LOCAL_ZIP -d $LOCAL_INFLATED_PATH;
+echo "Inflating left .zip [$LEFT_ZIP].";
+unzip -q $LEFT_ZIP -d $LEFT_INFLATED_PATH;
 if [ $? -ne 0 ]; then 
-	echo "Failed to inflate local .zip [$LOCAL_ZIP].";
+	echo "Failed to inflate left .zip [$LEFT_ZIP].";
 	exit -1;
 fi 
 
 echo "Generating list of files to serialize.";
-REMOTE_FILES=( $(find $REMOTE_INFLATED_PATH) );
-LOCAL_FILES=( $(find $LOCAL_INFLATED_PATH) );
+RIGHT_FILES=( $(find $RIGHT_INFLATED_PATH) );
+LEFT_FILES=( $(find $LEFT_INFLATED_PATH) );
 
-echo "Serializing remote files.";
-for file in ${REMOTE_FILES[@]}; do 
+echo "Serializing right files.";
+for file in ${RIGHT_FILES[@]}; do 
 	if [ ! -d $file ]; then 
-		cat $file >> $REMOTE_SERIALIZED_PATH;
+		cat $file >> $RIGHT_SERIALIZED_PATH;
 	fi
 done 
 
-echo "Serializing local files.";
-for file in ${LOCAL_FILES[@]}; do
+echo "Serializing left files.";
+for file in ${LEFT_FILES[@]}; do
 	if [ ! -d $file ]; then 
-		cat $file >> $LOCAL_SERIALIZED_PATH;
+		cat $file >> $LEFT_SERIALIZED_PATH;
 	fi
 done 
 
-LOCAL_DIGEST=`md5 -q $LOCAL_SERIALIZED_PATH`;
-REMOTE_DIGEST=`md5 -q $REMOTE_SERIALIZED_PATH`;
-echo "[$REMOTE_DIGEST] <- Remote digest";
-echo "[$LOCAL_DIGEST] <- Local digest";
+LEFT_DIGEST=`md5 -q $LEFT_SERIALIZED_PATH`;
+RIGHT_DIGEST=`md5 -q $RIGHT_SERIALIZED_PATH`;
+echo "[$RIGHT_DIGEST] <- Right digest";
+echo "[$LEFT_DIGEST] <- Left digest";
 
-if [ $LOCAL_DIGEST == $REMOTE_DIGEST ]; then 
+if [ $LEFT_DIGEST == $RIGHT_DIGEST ]; then 
 	echo "Cleaning up.";
 	rm -r $WORKING_DIR;
 	echo "[PASS]";
